import { db } from '@/lib/db'
import { matchResults, registrations, tournaments } from '@/lib/db/schema'
import { desc, eq, sql } from 'drizzle-orm'

export const dynamic = 'force-dynamic'

export default async function LeaderboardPage() {
  const rows = await db.select({ squadName: registrations.squadName, tournamentTitle: tournaments.title, points: sql<number>`sum(${matchResults.points})`, kills: sql<number>`sum(${matchResults.kills})` }).from(matchResults).innerJoin(registrations, eq(matchResults.registrationId, registrations.id)).innerJoin(tournaments, eq(registrations.tournamentId, tournaments.id)).where(eq(matchResults.status, 'approved')).groupBy(registrations.id, registrations.squadName, tournaments.title).orderBy(desc(sql`sum(${matchResults.points})`)).limit(50)
  return <main className="min-h-screen bg-background px-5 py-12 text-foreground lg:px-10"><div className="mx-auto max-w-5xl"><a href="/" className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground hover:text-primary">Back to arena</a><p className="mt-10 font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Verified results</p><h1 className="mt-3 font-display text-5xl font-bold uppercase">Leaderboard</h1><p className="mt-3 text-sm text-muted-foreground">Only referee-approved match results appear here.</p><div className="mt-8 overflow-x-auto border border-border bg-card"><table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-border font-mono text-[9px] uppercase tracking-[0.14em] text-muted-foreground"><th className="px-6 py-4">Rank</th><th className="px-6 py-4">Squad</th><th className="px-6 py-4">Tournament</th><th className="px-6 py-4">Kills</th><th className="px-6 py-4">Points</th></tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={`${row.squadName}-${row.tournamentTitle}`} className="border-b border-border/70 text-sm last:border-0"><td className="px-6 py-4 font-mono text-primary">{String(index + 1).padStart(2, '0')}</td><td className="px-6 py-4 font-semibold">{row.squadName || 'Solo player'}</td><td className="px-6 py-4 text-muted-foreground">{row.tournamentTitle}</td><td className="px-6 py-4">{row.kills}</td><td className="px-6 py-4 font-bold">{row.points}</td></tr>) : <tr><td colSpan={5} className="px-6 py-12 text-center text-sm text-muted-foreground">Approved results will appear after the first match.</td></tr>}</tbody></table></div></div></main>
}
